### ISSUE TITLE
you should add a User parameter...

### ISSUE THREAD

**Issue by klh** [alexjeffburke/node-git-exec#2]
First using exec leaves things abit open for command injection, 
consider using spawn instead or execFile.

secondly, you should add user to run the command as.

running node with forever, or things like that often ends up being run as a different user than the one doing the git operations so a git pull from origin/master would not be able to work without copying credentails around (different .ssh directory)

consider doing cmd="sudo -u "+$user+".......... ; 
instead

**Comment by alexjeffburke** [comment]
Thanks for your report. A much belated reply just to note that with a large number alternatives I am no longer supporting this code and consider it deprecated. As such, I am closing this issue.
