### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by MocanuMarius** [alexjeffburke/node-git-exec#3]
You can instead of this line of code here (22)

if (typeof args === 'string') {
    args = ['/bin/sh', '-c', args];
  }

Make it to be

if (typeof args === 'string') {
    args = ['bash', '-c', args];
  }

This way users with windows will be able to run this too, through the git bash shell which kind of everyone uses if they do dev on windows.

**Comment by alexjeffburke** [comment]
Thanks for your report. A much belated reply just to note that with a large number alternatives I am no longer supporting this code and consider it deprecated. As such, I am closing this issue.
